### ISSUE TITLE
NativeMultiplatformTasks failing

### ISSUE THREAD

**Issue by vivekgupta4Git** [Kotlin/Storytale#20]
The task NativeMultiplatformTasks exiting abruptly for the devices with Name iPhone 15 Pro and iPhone 15 Pro Max due to the       incomplete regex :
    `val deviceTypeMatches = Regex("""(com.apple.CoreSimulator.SimDeviceType.iPhone-[0-9A-Z\-]+)""").findAll(availableDeviceTypes).toList()`
by adding the regex to include small letters can resolve the issue. 
https://pl.kotl.in/TOB7dhGET

**Comment by JSMonk** [comment]
Hi @vivekgupta4Git.
Thank you for the issue.
Could you please make a PR with the change?
