### ISSUE TITLE
TextFieldColors does not work

### ISSUE THREAD

**Issue by pspmoe** [Kotlin/Storytale#23]
The same Compose widget displays differently in `Compose Desktop` and `Storytale`:

```kt
// Compose Desktop
fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        title = "Example"
    ) {
        TextField(
            value = "ABCDEFG",
            onValueChange = {},
            isError = true,
            supportingText = { Text("This is a supporting text!") }
        )
    }
}
```

Display:
![image](https://github.com/user-attachments/assets/3cb7b1d2-0ffa-48aa-af29-47c683c75084)

```kt
// Storytale
val `TextField Story` by story {
    TextField(
        value = "ABCDEFG",
        onValueChange = {},
        isError = true,
        supportingText = { Text("This is a supporting text!") }
    )
}
```

Display:
![image](https://github.com/user-attachments/assets/3eccc7c6-cdef-47bf-9c3d-c5e533a8a877)

The `SupportingText` colors of the two are different. The expected color is red, but the actual color is black.

Also, specifying `TextFieldDefaults.colors()` in the `TextField` has no effect either, all colors remain as they are.

**Comment by whitescent** [comment]
Thank you for the report, this is because Storytale currently uses a separate Theme for the Gallery App, but does not apply the `MaterialTheme` to the story component
